apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-db-backup-pvc
  namespace: cs1
  labels:
    foundationservices.cloudpak.ibm.com: cs-db-data
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem