apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cs-db-backup-rolebinding
  namespace: cs1
  labels:
    foundationservices.cloudpak.ibm.com: cs-db-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cs-db-backup-role
  namespace: cs1
subjects:
- kind: ServiceAccount
  name: cs-db-backup-sa
  namespace: cs1